spring.application.name=api-gateway
server.port = 9000

# Base URLs for Gateway Routes
user.service.base-url=http://localhost:8080
device.service.base-url=http://localhost:8081
usage.service.base-url=http://localhost:8083
ingestion.service.base-url=http://localhost:8082
insight.service.base-url=http://localhost:8085

# Expose Circuit Breaker Actuator Endpoints
management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents,metrics
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.metrics.enabled=true

# Resilience4j Config for Gateway Circuit Breaker
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
