spring.application.name=insight-service
server.port = 8085

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.metrics.tags.application=${spring.application.name}

usage.service.url = http://localhost:8083/api/v1/usage

spring.ai.ollama.chat.model=llama2
spring.ai.ollama.init.pull-model-strategy=never