spring.application.name=usage-service
server.port = 8083

# Actuator & Prometheus (scraped by Prometheus in docker-compose)
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.metrics.tags.application=${spring.application.name}

#Kafka - consumer
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=usage-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=com.homeenergytracker.ingestion_service.kafka.event.EnergyUsageEvent:com.homeenergytracker.usage_service.kafka.event.EnergyUsageEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#Kafka - producer
spring.kafka.template.default-topic=energy-alerts
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


#Influx DB Configuration
influx.url=http://localhost:8072
influx.token=${INFLUX_TOKEN}
influx.org=home-energy-tracker
influx.bucket=usage-bucket


device.service.url=http://localhost:8081/api/v1/device
user.service.url=http://localhost:8080/api/v1/user


#Resilience4j Circuit breaker config

resilience4j.circuitbreaker.instances.userService.sliding-window-size=10
resilience4j.circuitbreaker.instances.userService.sliding-window-type=count_based
resilience4j.circuitbreaker.instances.userService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s


#Resilence4j Retry config

resilience4j.retry.instances.userService.max-attempts=3
resilience4j.retry.instances.userService.wait-duration=500ms
resilience4j.retry.instances.userService.enable-exponential-backoff=true
resilience4j.retry.instances.userService.exponential-backoff-multiplier=2




